language: android

android:
  components:
    - platform-tools
    - tools
    - tools
    - android-24
    - build-tools-24.0.0
    - extra-android-support
    - extra-android-m2repository

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle