language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-25
    - build-tools-25.0.2
    - extra-android-support
    - extra-android-m2repository

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle